### ISSUE TITLE
LegalParticipant credential type should be LegalPerson instead

### ISSUE THREAD

**Issue by markus-hentsch** [SovereignCloudStack/gx-credential-generator#120] opened 2024-09-20 12:59 UTC
The current implementation creates a credential of type `gx:LegalParticipant`[^1] but calls it "Legal Person".
The Gaia-X schema does not define a `gx:LegalParticipant` class, only `gx:LegalPerson`[^2].

The Gaia-X Trust Framework defines Legal Person to be an instance of the abstract parent class Legal Participant[^3].
Furthemore it states:

> Instances of a Participant neither being a legal nor a natural person are prohibited.

From this I conclude that plain usage of `gx:LegalParticipant` as type of Gaia-X Credentials is prohibited. The implementation should be changed to generate a `gx:LegalPerson` type credential instead.

[^1]: https://github.com/SovereignCloudStack/gx-credential-generator/blob/0de383e550c5939aeb2020ebd97184535e873935/generator/discovery/csp_generator.py#L106

[^2]: https://github.com/SovereignCloudStack/gx-credential-generator/blob/0de383e550c5939aeb2020ebd97184535e873935/generator/common/gx_schema.py#L932

[^3]: https://docs.gaia-x.eu/policy-rules-committee/trust-framework/22.10/participant/

**Comment by markus-hentsch** [comment] 2024-09-20 13:04
Most likely we were mislead by the gaia-x-101 workshop example from Gaia-X which does the same: https://gitlab.com/gaia-x/lab/workshops/gaia-x-101/-/blob/e0b01980eead64c0a20fec4643659b4c9d9f3331/templates/participant.j2#L15

**Comment by markus-hentsch** [comment] 2024-09-20 13:13
Now that I did a quick test with some local examples, I noticed that the Compliance API does *not* accept `gx:LegalPerson`:

```
{"message":"VerifiableCrdential contains a shape that is not defined in registry shapes",
"error":"Conflict","statusCode":409}
```
*(note: the typo in "VerifiableCrdential" is verbatim from the API response)*

Looking at the shape registry[^1] included in the `@context` for the VC, there is no `gx:LegalPerson`, only `gx:LegalParticipant` which is the exact opposite to our `gx_schema.py`[^2] and my interpretation of the statement "Instances of a Participant neither being a legal nor a natural person are prohibited."[^3]

[^1]: https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#

[^2]: https://github.com/SovereignCloudStack/gx-credential-generator/blob/0de383e550c5939aeb2020ebd97184535e873935/generator/common/gx_schema.py#L932

[^3]: https://docs.gaia-x.eu/policy-rules-committee/trust-framework/22.10/participant/

**Comment by anjastrunk** [comment] 2024-10-14 18:41
Both [Trust Framework (v22.10)](https://docs.gaia-x.eu/policy-rules-committee/trust-framework/22.10/participant/) as well as [Compliance Framework (v24.06)](https://docs.gaia-x.eu/policy-rules-committee/compliance-document/24.06/Participant/) use the term `LegalPerson`. Compliance Service expects `LegalParticipant` instead, which is in sync with shapes retrieved from GXDCH Registry. As Gaia-X propagates registry as single-source-of-truth, hence `LegalParticipant` is correct.

The discrepancy between Trust Framework/Compliance Document and Compliance Service/Registry is a bug, caused by accident as shapes for Tagus release are written by hand. This bug is already known and fixed in Loire release, where shapes are generated automatically from [Service Ontology](https://gitlab.com/gaia-x/technical-committee/service-characteristics-working-group/service-characteristics/-/tree/develop/single-point-of-truth?ref_type=heads) modeled in linkML. For Loire release, term `LegalPerson` is correct.

**Closed by anjastrunk** 2024-10-14 18:41 UTC
